mockoon/mockoon

src/app/libs/dummy-helpers.lib.ts

Add a default value the `queryParam` and `header`.
This allows for configuring query params like `limit` but give it a default if not passed.
**Mockoon**
```
{
"data": [
{{#repeat (queryParam 'limit' 5)}}
{
"name": "{{firstName}} {{lastName}}",
}
{{/repeat}}
]
}
```
**Without Param**
**URL:** `localhost:3030/contacts/`
```json
{
"data": [
{
"name": "Cecilia Higgins"
},
{
"name": "Drew Coolidge"
},
{
"name": "Benito Mullens"
},
{
"name": "Katelin Carroll"
},
{
"name": "Florance Castleman"
}
]
}
```
**With Param**
**URL:** `localhost:3030/contacts/?limit=2`
```json
{
"data": [
{
"name": "Cory Chapman"
},
{
"name": "Lorelei White"
}
]
}
```

Added default value to queryParam and header

---

src/app/app.component.html
src/app/app.component.ts

I was missing the feature to "pretty-print" a copy/pasted JSON body within Mockoon. So I added it on click of the "body" icon, because it was one of the things I tried clicking on when looking for this feature.

Pretty-print JSON bodies

---

src/app/components/environment-logs.component.html
src/app/components/environment-logs.component.ts
src/app/services/data.service.ts
src/app/services/server.service.ts
src/app/stores/reducer.ts
src/app/stores/store.ts
src/app/types/misc.type.ts
src/app/types/server.type.ts
test/environment-logs.spec.ts

I create two tabs in environment logs view: Request and Response. 
Each call have your request and response data logged in these tabs. 
This pull request implement the feature described in #138
This is described in #138
I used the default Dev env environment and made all calls with firefox browser. 
I call /answer to test the mocked responses, /test to test the 404 error responses.
I create another environment with a /test route with the response (200, {}, timeout 5000), using 3001 port. I enable the Dev env proxy setting to the another environment (http://127.0.0.1:3001/). When I call /test on Dev env I can see the message "No response yet", and after 5 seconds I can see the response.
I stopped the …

Implement logs for responses

---

src/app/app.component.ts

- Closes #189 where UI wasn't refreshing after a file choice due to callback running outside zone.js
- Migrate to Electron promisified dialog

Migrate to Electron 5+ dialog promise instead of callback

---

README.md

This PR simply adds a hint to the Download section in the README.md that the package is now also available through the arch user repository.
Since I neither wanted to use the snap version of Mockoon, nor manually download and install the .deb file, I created a `PKGBUILD` and pushed it to the AUR (https://aur.archlinux.org/packages/mockoon-bin/).
Execute `yay -S mockoon-bin` (or use any other AUR helper instead of yay) on your Arch Linux machine. The debian file is automatically fetched from github and installed.

Add AUR download hint to README

---

src/app/app.component.html
src/app/app.component.ts
src/app/components/context-menu.component.ts
src/app/libs/migrations.lib.ts
src/app/services/environments.service.ts
src/app/services/server.service.ts
src/app/stores/reducer.ts
src/app/types/route.type.ts
src/styles.scss
test/data/basic-data/environments.json
test/data/basic-data/settings.json
test/data/dev/environments.json
test/data/dev/settings.json
test/data/first-load/settings.json
test/data/proxy/environments.json
test/data/proxy/settings.json
test/data/responses-rules/environments.json
test/data/responses-rules/settings.json
test/enable-disabling-routes.spec.ts
test/lib/helpers.ts
test/routes-create-delete.spec.ts

Implements a feature do disable/enable a route. When
Issue #106 
I use the basic-data environment, start the environment and made a call to "/anwser". Then I disable the route, restart the server and made another call to "/answer", now the route is not caught. I enable the route and restart the server again and made the call, the route is caught.
**Screenshots**
Closes #106

Feature support route disabling

---

src/app/services/environments.service.ts
src/app/stores/store.ts
test/environments-create-delete.spec.ts
test/lib/helpers.ts

On create or duplicate an environment it's generate a new unused port to it. The port is chosen based on the active environment port. If any of the ten next ports is unused by an environment, this port is chosen. Else a random unused port is generated. The default port, when there's no environments, remains the 3000.
Issue #192
I tested creating a environment if when there's no environments. Creating and duplicating more than ten environments selecting the first on any new environment.
Closes #192

Generate a unused port to a new environment

---

src/app/app.component.ts
src/app/libs/utils.lib.ts
src/app/services/server.service.ts
src/app/stores/reducer.ts

Content-Type was extracted from route/environment in a case sensitive manner which lead to wrong content type being applied to the route if capitalized one was not found. This could result in a JSON parsing error.
Also, uses includes instead of === to compare headers as additional info may be present in header (charset, etc)

Fix bug with case sensitive Content-Type comparison

---

src/app/components/environment-logs.component.html
test/environment-logs.spec.ts
test/proxy.spec.ts

Fixed css in order not to hide environment log entries icon.
Issue #238 
1. Start the server 
2. Make a req
`curl    http://localhost:3000/bigtest/api/v1/refreshwidget/bigonee`
3. Add the route 
4. Make again a req
`curl    http://localhost:3000/bigtest/api/v1/refreshwidget/bigonee`
Check the environment logs 
Closes #238

Fix environment log hidden icon - #238

---

scripts/aur-version-bump/Dockerfile
scripts/aur-version-bump/README.md
scripts/aur-version-bump/bump
scripts/aur-version-bump/sudoers

Since you had trouble making version updates to the AUR PKGBUILD which I added, I figured I could provide an Arch Linux container with a small script that does just that.
Well, using this, it shouldn't be necessary anymore to contact me to bump the version number of the AUR package ;)
Follow the steps provided in the README.md to build and run the container. To see if it's working, you can simply use the current version "1.7.0" as parameter to the docker run command - git should then output that there have been no changes.
Happy Holidays,
Lukas

Add arch linux container to bump AUR package version

---

src/app/services/openapi-converter.service.ts

Added a null check for the host field when importing a swagger v2 file. As the types correctly indicate, the host field is optional, it wasn't treated this way however.
Two side notes:
- Optional chaining would have been preferred, however the current angular compiler version doesn't allow a recent enough TypeScript version, which brings the feature (>= 3.7).
- These sort of bugs are preventable with the TypeScript compiler option `strict: true`. Not sure if it's left out intentionally, however when enabling it locally, it showed up quite some more type errors.
https://github.com/mockoon/mockoon/issues/326
Import the swagger v2 file (or any other one without the `host` field) from the linked issue: it should work using the …

Add null check for swagger v2 host field when importing

---

.gitignore
src/app/services/environments.service.ts
test/data/environment-logs/environments.json
test/suites/environment-logs.spec.ts

Check the prefix of the active environment when creating the route from the
environment logs. If the prefix is present in the request path then remove it
when creating the route.
Manual testing on my local machine to verify behaviour, automated tests updated to cover the functionality.
Modify the environment-logs test spec to add a prefix and verify that the auto
mock removes the prefix in the created route.
Closes #333

 Remove api prefix when auto-mocking #333

---

package-lock.json
package.json
src/app/libs/template-parser.lib.ts
test/data/templating/environments.json
test/lib/helpers.ts
test/lib/models.ts
test/suites/templating.spec.ts

{{objectId}} will generate a random MongoDB's ObjectId in the format of: 5f7c1ee149354fbcb2f9189b
Closes #342 
We use ObjectId as id and we expose them on our REST APIs

Generate random ObjectId for mocking mongodb

---

src/app/enums/analytics-events.enum.ts
src/app/enums/messages.enum.ts
src/app/services/import-export.service.ts
src/app/services/ipc.service.ts
src/electron-main.js
test/data/export/environments.json
test/suites/export.spec.ts

Adds the **Export current environment to a file (JSON)** option to the Import/export menu in Mockoon's format.
The implementation in Import/Export Service is based off `exportAllEnvironments`, except the active environment is retrieved instead of the whole environments list.
To reduce code duplication a little, the `exportDataToFilePath` function was extracted from `exportAllEnvironments` and reused in `exportActiveEnvironment`.
Import/export selected environment only https://github.com/mockoon/mockoon/issues/251
Implementing the feature mentioned in the related issue (#251).
A second environment fixture was added to `test/data/export/environments.json`.
The test for exporting all environments was …

Add option to export selected environment to JSON

---

src/app/app.component.html
src/app/app.component.ts
src/app/services/schemas-builder.service.ts
src/app/stores/store.ts
test/suites/ui-interactions.spec.ts

Closes #299
**Some details prior to the technical ones**
Since this is a small, contained feature, I took the initiative and implemented it without bugging you before doing the work.
However, if you don't like the implementation, I'll apply any change requests you make.
I also took the initiative to create the following behavior:
- When there are no headers, or no rules, the respective tab label does not contain any number indication. (So it is _Headers_ and _Rules_.)
- When one of the two tabs contains more-than-zero items, its label starts containing the count. (Examples: _Headers (1)_, _Rules (7)_ etc.)
- 2 methods are added in `src/app/app.component.ts` that calculate the suffixes for the tab labels. I wanted to follow the naming …

Add route headers and rules count in tab

---

src/renderer/app/app.component.html
src/renderer/app/app.component.ts
src/renderer/app/components/environments-menu/environments-menu.component.html
src/renderer/app/constants/messages.constants.ts
src/renderer/app/services/schemas-builder.service.ts
src/renderer/app/stores/reducer.ts
test/data/environment-hostname-restriction/all/environments.json
test/data/environment-hostname-restriction/localhost/environments.json
test/lib/fetch.ts
test/lib/helpers.ts
test/suites/environment-hostname-restriction.spec.ts
test/suites/migrations.spec.ts

Closes #469 
Changes HTTPS settings to Server Settings
Changes Enable checkbox to HTTPS
Adds Localhost Only checkbox under Server Settings
Makes the environments menu show the configured hostname instead of a static 0.0.0.0
The Localhost Only checkbox just determines if 127.0.0.1 or 0.0.0.0 gets set as the hostname configuration value.

Closes mockoon/mockoon#469

---

src/renderer/app/components/move-route-modal/duplicate-route-modal.component.html
test/suites/routes-duplicate-to-env.spec.ts

Add test for the display of hostname and port
Closes #532
Closes #[insert_issue_number_here]
**Checklist**

Fix "duplicate to environment" UI when the env is unnamed

---

packages/commons-server/src/libs/templating-helpers/faker-wrapper.ts
packages/commons-server/test/suites/templating-helpers/faker-wrapper.spec.ts

-Make the Faker wrapper returns the actual faker's function value (string, number, etc.). Like this, the `faker` helper is compatible with other helpers that needs other things than strings (`int`, `if`, etc.)
Closes #699
**Checklist**

Fix `faker` helper returning a SafeString

---

packages/commons-server/src/libs/templating-helpers/helpers.ts
packages/commons-server/test/suites/templating-helpers/helpers.spec.ts

Also fix the `repeat` helper overwriting nested contexts. 
Closes #706
**Checklist**

Fix `setVar` helper not working in nested block helpers

---

packages/desktop/src/main/libs/watch-file.ts
packages/desktop/src/renderer/app/services/settings.service.ts

Save method was sometimes saving the initial state of the store's settings. 
Closes #751
**Checklist**

Fix settings save race condition

---

packages/commons-server/src/libs/templating-helpers/helpers.ts
packages/commons-server/test/suites/templating-helpers/faker-wrapper.spec.ts
packages/commons-server/test/suites/templating-helpers/helpers.spec.ts

Revert to using `options.data` instead of `this` or `root` due to incompatibility between Handlebars' `each` implementation and `repeat`. Now all variables are scoped and available by using `@`.
Closes #793
**Checklist**

Fix `setVar` not working in `each`

---

packages/commons-server/src/libs/server/server.ts
packages/commons-server/src/libs/templating-helpers/data-helpers.ts
packages/commons-server/test/suites/templating-helpers/data-helpers.spec.ts
packages/desktop/test/data/mock-envs/databuckets.json
packages/desktop/test/specs/databuckets.spec.ts

- fix data helpers not able to get retrieve falsy values
- fix dataRaw helper retrieving wrong object path
- fix data bucket direct linking of JSON content not working
Closes #841, closes #842
**Checklist**

Data bucket fixes

---

packages/commons-server/src/libs/utils.ts
packages/commons/src/models/server.model.ts
packages/desktop/src/renderer/app/components/environment-logs/environment-logs.component.html
packages/desktop/src/renderer/app/models/environment-logs.model.ts
packages/desktop/src/renderer/app/services/data.service.ts
packages/desktop/test/libs/http.ts
packages/desktop/test/libs/models.ts
packages/desktop/test/specs/environment-logs.spec.ts

Closes #852
I've been added a new property  `statusMessage` in `Transaction.response` located in `packages\commons\src\models\server.model.ts` for getting the statusMessage in "Logs" tab and some other places:
- `function CreateTransaction` in packages\commons-server\src\libs\utils.ts that converts a pair of `Request` and `Response` objects in a `Transaction` object
- `EnvironmentLogResponse` in packages\desktop\src\renderer\app\models\environment-logs.model.ts for showing the information from modified `Transaction` in "Logs" tab
- `function formatLog` in packages\desktop\src\renderer\app\services\data.service.ts for converting the `Transaction` object in 
`EnvironmentLogResponse` object.
- added a new item in "General" section of "Response" tab in …

Add response.statusMessage data information in environment logs

---

packages/commons-server/src/libs/templating-helpers/helpers.ts
packages/commons-server/test/suites/templating-helpers/helpers.spec.ts

Closes #873
This adds a `dateFormat` helper that works like this :
```
{{dateFormat '2022-02-01' 'YYYY'}}
```
And output :
```
2022
```
**Checklist**

Add dateFormat helper

---

packages/commons-server/src/libs/server/server.ts

Fix data buckets containing request helpers being generated twice

---

packages/commons-server/src/libs/server/server.ts
packages/commons-server/src/libs/templating-helpers/data-helpers.ts
packages/commons-server/src/libs/templating-helpers/request-helpers.ts
packages/commons-server/src/typings.d.ts
packages/commons-server/test/suites/templating-helpers/data-helpers.spec.ts
packages/commons-server/test/suites/templating-helpers/request-helpers.spec.ts

I want to propose this new helper. The impact is very little and it is simple to be used, but can be very useful in many cases.
The idea is to be able to set the response status inside the template.
Imagine a route like this:
test/:id
and a data bucket with name `testdata` and the following content:
```
{
"data": {
"001": {
"id": "001",
"name": "Item 1"
},
"002": {
"id": "002",
"name": "Item 2"
}
}
}
```
now using a template like this:
```handlebar
{{setVar 'selection' (concat 'data.' (urlParam 'id'))}}
{{#if (dataRaw 'testdata' @selection true)}}
{{data 'testdata' @selection}}
{{else}}
{{status 404}}
{
"error": "NOT_EXISTS"
}
{{/if}}
```
we have a routes where we can return 200 with data if the data exists in the bucket
GET /test/001
or 404 if the …

Add "status" request helper

---

packages/commons-server/src/libs/openapi-converter.ts
packages/commons-server/test/data/openapi/openapi-v3.yaml
packages/commons-server/test/data/openapi/swagger.json
packages/commons-server/test/suites/openapi-converter/openapi-converter.spec.ts

Closes #962 
When importing an OpenAPI specification file, the `examples` property of the specification is used to generate new route responses. Each example is transformed in a new route response and the default route response is the one generated from the `schema` property.
**Checklist**

Feature/962 Use OpenAPI examples

---

README.md
backers.md

The Github logo doesn't appear when using a light theme. This updates the Github logo to switch between light and dark theme so that it's always visible.

Fix Github logo for light and dark themes

---

packages/desktop/src/main/libs/ipc.ts
packages/desktop/src/renderer/app/app.component.ts
packages/desktop/src/renderer/app/components/context-menu/context-menus.ts
packages/desktop/src/renderer/app/components/svg/svg.component.html
packages/desktop/src/renderer/app/components/svg/svg.component.ts
packages/desktop/src/renderer/app/constants/desktop-messages.constants.ts
packages/desktop/src/renderer/app/models/context-menu.model.ts
packages/desktop/src/renderer/app/models/messages.model.ts
packages/desktop/src/renderer/app/services/dialogs.service.ts
packages/desktop/src/renderer/app/services/environments.service.ts
packages/desktop/src/renderer/app/stores/actions.ts
packages/desktop/src/renderer/app/stores/reducer.ts
packages/desktop/test/libs/context-menu.ts

Add context menu entry to move an environment file

---

packages/desktop/src/renderer/app/components/menus/routes-menu/routes-menu.component.html
packages/desktop/src/renderer/app/stores/reducer-utils.ts
packages/desktop/src/renderer/app/stores/reducer.ts

Automatically uncollapse parent folders of selected route after a search Closes #960
**Checklist**

Allow search of hidden routes in the desktop app

---

packages/cli/README.md

May be useful for teams using multiple platforms (as we do).
Hopefully save somebody some time :)
https://github.com/mockoon/mockoon/issues/895

docs: cross platform disabling std logging

---

.github/workflows/ci.yml
packages/cli/README.md
packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/commands/dockerize.ts
packages/cli/src/libs/data.ts
packages/cli/test/specs/data-loading.spec.ts
packages/cli/test/specs/data-validation.spec.ts
packages/cli/test/specs/legacy-export-file.spec.ts
packages/cli/test/specs/logging.spec.ts
packages/cli/test/specs/mock-file-relative-path.spec.ts
packages/cli/test/specs/openapi.spec.ts
packages/cli/test/specs/run-multiple-mocks.spec.ts
packages/cli/test/specs/run-single-mock.spec.ts
packages/commons-server/package-lock.json
packages/commons-server/package.json
packages/commons/package-lock.json
packages/desktop/package-lock.json
packages/desktop/package.json
packages/desktop/src/main/libs/update.ts
packages/serverless/package-lock.json
packages/serverless/package.json

Node 16 is reaching EOL, remove it from supported engines and replace Axios by fetch that is now available.
**Checklist**

Remove Node 16

---

packages/commons-server/package-lock.json
packages/commons/src/constants/environment-schema.constants.ts
packages/commons/src/models/route.model.ts
packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.ts
packages/desktop/src/renderer/styles/styles.scss
packages/desktop/test/data/mock-envs/global-route.json
packages/desktop/test/specs/global-route.spec.ts
packages/desktop/test/specs/ui-interactions.spec.ts

Fallback mode already allows for global route with rules, but the possibility to use this global route on all methods is missing. Closes #221
**Checklist**

Add an "all" methods choice

---

packages/desktop/src/main/libs/main-window.ts
packages/desktop/src/renderer/app/directives/resize-column.directive.ts

Rely on the window state to maximize before showing the BrowserWindow. This avoid jumping from a smaller size to a maximize state and reduce the size of the menus. Do not save the settings when restoring, but only after a resize event or a user interaction. Also improve performances by only saving after mouse up or resize event.
Closes #1167
**Checklist**

Fix menu sizes not being restored in desktop app

---

packages/desktop/src/renderer/app/app.module.ts
packages/desktop/src/renderer/app/components/menus/databuckets-menu/databuckets-menu.component.html
packages/desktop/src/renderer/app/components/menus/databuckets-menu/databuckets-menu.component.ts
packages/desktop/src/renderer/app/components/menus/environments-menu/environments-menu.component.html
packages/desktop/src/renderer/app/components/menus/environments-menu/environments-menu.component.ts
packages/desktop/src/renderer/app/components/menus/routes-menu/routes-menu.component.html
packages/desktop/src/renderer/app/components/menus/routes-menu/routes-menu.component.ts
packages/desktop/src/renderer/app/components/modals/templates-modal/templates-modal.component.ts
packages/desktop/src/renderer/app/directives/scroll-to-active.directive.ts
packages/desktop/src/renderer/app/libs/utils.lib.ts
packages/desktop/src/renderer/app/models/ui.model.ts
packages/desktop/src/renderer/app/services/command-palette.service.ts
packages/desktop/src/renderer/app/services/environments.service.ts
packages/desktop/src/renderer/app/services/ui.service.ts

Use a directive focusing elements with .active class instead of event emitters. This also neatly refocus menu items when navigating between tabs
**Checklist**

Simplify desktop app menu scroll to items

---

packages/commons-server/src/libs/filters.ts
packages/commons-server/src/libs/server/crud.ts
packages/commons-server/src/libs/utils.ts
packages/commons-server/test/suites/filters.spec.ts
packages/commons-server/test/suites/utils.spec.ts
packages/desktop/test/data/mock-envs/crud.json
packages/desktop/test/specs/crud.spec.ts

Adds **searching and filtering** functionality to CRUD routes using query params
Adds the ability to use query parameters in the form of `[property]_[operator]`. For instance, if you want to filter an array of objects by their `status` property, you can use:
```
GET /path?status_eq=success
```
With this PR, the following operators are introduced:
| Operator | Description                                   | Example             |
| -------- | --------------------------------------------- | ------------------- |
| `eq`     | Filters by equality                           | `status_eq=success` |
| `ne`     | Filters by inequality                         | `status_ne=error`   |
| `gt`     | Filters by greater                            | `price_gt=10`       |
| `gte`    | Filters by greater or …

Add searching and filtering for CRUD routes with query params

---

packages/desktop/src/renderer/app/stores/reducer-utils.ts

Updating a property that doesn't require a restart was removing the restart needed state.
**Checklist**

Fix restart needed

---

packages/desktop/src/main/app.ts
packages/desktop/src/main/libs/main-window.ts
packages/desktop/src/main/libs/menu.ts

- Add a new Close window option to enable cmd+w shortcut
- Make cmd+q and dock right-click->quit to permanently quit the application
Closes 1097
**Checklist**

Update app close options for macOS

---

packages/desktop/src/renderer/app/components/environment-logs/environment-logs.component.html

Even if the call was caught by a route (`request.route` is present), it could have go through the proxy and marked as proxied.  Closes #1267
**Checklist**

Update logs interface to show answers proxied through a fallback route

---

packages/commons-server/src/constants/common.constants.ts
packages/commons-server/src/libs/server/server.ts
packages/commons-server/src/libs/utils.ts

Some clients uses vendor specific JSON Content-Type like `application/vnd.xxxxxxx+json`. This add support for these types in the request body parsing and rules interpreter. Closes #1269
**Checklist**

Add support for vendor specific JSON content types

---

packages/cli/src/commands/start.ts

Due to bad usage of chalk lib (without listing it as a dependency, or peerDep), the CLI could crash when run in a project using an incompatible version (like v5 which is ESM only).
Closes #1276
**Checklist**

Remove CLI's chalk usage

---

packages/desktop/src/renderer/app/components/editable-element/editable-element.component.ts
packages/desktop/src/renderer/styles/boostrap-overrides.scss

Since last patch, input was not hidden after a click outside of the input Also remove some very old CSS causing letter blinking Closes #1279
**Checklist**

Fix editable element component not propagating blur event

---

packages/commons-server/src/libs/templating-helpers/helpers/someOf.ts
packages/commons-server/test/suites/templating-helpers/helpers.spec.ts

Use JSON.Stringify in `someOf` helper instead of custom thing as it would return an array with one empty string when there is no element instead of just an empty array. Closes #1289
**Checklist**

Use JSON.Stringify in `someOf` helper

---

packages/commons-server/src/libs/openapi-converter.ts
packages/desktop/test/data/res/import-openapi/references/custom-schema-v3.json
packages/desktop/test/data/res/import-openapi/samples/custom-schema-v3.yaml

Fix `example`, `default`, etc not being picked up when `schema` contains `allof`, `oneOf` or `anyOf`. Closes #948
**Checklist**

Support for OpenAPI schema allOf, oneOf, etc.

---

packages/desktop/scripts/aur-version-bump/README.md
packages/desktop/scripts/aur-version-bump/bump

Hi, as just discussed via email, here is the PR that addresses the problem with the AUR package update:
The issue was that the initial script had never assumed that the `source` actually changes, aside from the version of course. So once you updated the url with `amd64`, it was only really changed for the checksum generation, but not actually for the `source` field itself. See specifically the line [here](https://github.com/mockoon/mockoon/compare/main...Spissable:mockoon:fix-aur-version-bump?expand=1#diff-38db9d1bd110ea7f464de5a9ef6978ce085254bf68c2cfe1bc3ab6485209ccafR22) which overwrites the `source` field in the `PKGBUILD`.
As a little QoL, I also added the `pkgrel` as a param here. Apparently we were forever stuck with the number `2`, which while not harmful, it wasn't quite right, …

Overwrite `source` and `pkgrel` in aur package on every package release

---

packages/commons-server/src/libs/server/server.ts

Firebase functions always populate the body with an empty object, even if there is no body, and no Content-Type header. rawBody presence needs to be checked too.
Closes #1413
**Checklist**

Fix null pointer when calling a firebase function without a body

---

packages/desktop/src/renderer/app/app.module.ts

This is apparently due to a change in Angular 15. We should use FormControl.disable() but let's stick with [attr.disabled] for now Closes #1517
**Checklist**

Fix rules inputs not staying disabled after navigation

---

packages/commons-server/src/libs/response-rules-interpreter.ts
packages/commons-server/test/suites/response-rules/response-rules-interpreter.spec.ts
packages/commons/src/constants/environment-schema.constants.ts
packages/commons/src/models/route.model.ts
packages/desktop/src/renderer/app/components/custom-select/custom-select.component.html
packages/desktop/src/renderer/app/components/custom-select/custom-select.component.ts
packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.html
packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.ts
packages/desktop/src/renderer/app/components/route-response-rules/route-response-rules.component.html
packages/desktop/src/renderer/app/components/route-response-rules/route-response-rules.component.ts
packages/desktop/test/libs/routes.ts
packages/desktop/test/libs/utils.ts

also indent custom select entries when there are categories remove categories from the method custom select as all entries are HTTP methods anyway Closes #1468, closes #1467
**Checklist**

Add two new rules: path and method

---

packages/commons-server/package-lock.json
packages/commons-server/package.json
packages/commons-server/src/libs/requests.ts
packages/commons-server/src/libs/server/server.ts
packages/commons-server/test/suites/requests.spec.ts
packages/commons-server/test/suites/server/ws.spec.ts
packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.html
packages/desktop/src/renderer/app/components/route-response-rules/route-response-rules.component.html
packages/desktop/src/renderer/app/components/route-response-rules/route-response-rules.component.ts
packages/desktop/src/renderer/app/constants/texts.constant.ts

Initial WebSocket release (#83) has a limitation on not supporting named path variables. This is because, the used library does not implement it. But this PR implements the support on path variables using the same library, called [path-to-regexp](https://www.npmjs.com/package/path-to-regexp) used by [express.js](https://github.com/expressjs/express/blob/master/package.json#L50) itself.
In turn, now `Route parameter` option can be selected when defining a rule.
Note: Since broadcasting events are independent of client input, these path parameters does not make applicable. Anyway, the rules are already disabled in broadcasting endpoints.
**Checklist**
Closes #1495

Support named path parameters for websocket routes #1495

---

packages/commons-server/src/libs/server/crud.ts
packages/desktop/test/specs/crud.spec.ts

Fix bug where updateById CRUD operation was not keeping custom Ids

---

packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.html
packages/desktop/src/renderer/app/stores/reducer-utils.ts
packages/desktop/src/renderer/app/stores/reducer.ts

If use navigates to a tab not available in the CRUD default response (the CRUD operations response) on a secondary response, like "callbacks" or "Settings", and switch back to the default response, the tab stays focused even if it doesn't exists. Also fix CSS grid classes not being correctly selected depending on the route type. Closes #1552
**Checklist**

Fix CRUD responses tab switching

---

packages/cloud/src/models/deploy-instance.model.ts
packages/desktop/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.html
packages/desktop/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.ts

Add option to disable admin API during cloud deployment

---

packages/commons-server/src/libs/server/server.ts
packages/commons-server/test/specs/server/server-databucket-generation.test.ts
packages/commons-server/test/specs/templating-helpers/data-helpers.test.ts

Avoid "zipcode" being detected as a request helper (because it contains "ip") Closes #1589
**Checklist**

Update data bucket request helpers regex to avoid false positives

---

packages/commons-server/src/libs/requests.ts
packages/commons-server/src/libs/response-rules-interpreter.ts
packages/commons-server/src/libs/server/events-listeners.ts
packages/commons-server/src/libs/server/server.ts
packages/commons-server/src/libs/utils.ts
packages/commons-server/test/specs/requests.test.ts
packages/commons-server/test/specs/response-rules/response-rules-interpreter.test.ts
packages/desktop/src/renderer/app/components/route-response-rules/route-response-rules.component.ts

Path rule can now compare the value against the original path (/test/:id) and the effective path (/test/123).
Closes #1605
**Checklist**

All path rule comparison against original path with parameters

---

packages/commons-server/src/libs/server/server.ts
packages/commons-server/test/specs/server/server-body-parsing.test.ts

Multiple fields having the same names without brackets are now stored as an array Closes #1613
**Checklist**

Add support for multipart/form-data arrays without using the brackets

---

packages/commons-server/package-lock.json
packages/commons-server/package.json
packages/commons-server/src/libs/server/server.ts
packages/commons-server/test/specs/server/ws.test.ts
packages/desktop/test/data/mock-envs/ws.json
packages/desktop/test/specs/ws.spec.ts

WS connections were hanging when the wrong path was provided, or when an API prefix was present. Also fixes a mistake where an HTTP route was always created with the same name as the WS route. Closes #1612
**Checklist**

Fix websockets hanging when API prefix is present

---

packages/commons-server/src/libs/templating-helpers/data-helpers.ts
packages/commons-server/src/libs/templating-helpers/helpers/concat.ts
packages/commons-server/src/libs/templating-helpers/helpers/index.ts
packages/commons-server/src/libs/templating-helpers/helpers/objectMerge.ts
packages/commons-server/src/libs/utils.ts
packages/commons-server/test/specs/templating-helpers/data-helpers.test.ts
packages/commons-server/test/specs/templating-helpers/helpers.test.ts
packages/desktop/src/renderer/app/constants/autocomplete.constant.ts

Add objectMerge helper, add array support in concat and setData 'merge'

---

packages/cli/README.md
packages/cli/src/commands/start.ts
packages/cli/src/libs/data.ts
packages/commons-server/src/libs/server/server.ts
packages/commons-server/src/libs/utils.ts
packages/serverless/README.md

- new proxy CLI flag can either be "enabled" or "disabled"
- also update the disabled routes option, to allow wildcard "*"
- fix a bug where routes couldn't be disabled by keyword as advertised in the doc
Closes #1024
**Checklist**

Add a proxy flag to the CLI to override the proxy mode

---

packages/commons-server/src/libs/response-rules-interpreter.ts
packages/commons-server/test/specs/response-rules/response-rules-interpreter.test.ts

Null and empty array rules were needing a modifier to work, which doesn't really make sense. Also, the default body string value was removed if the request contains a valid content type, even if parsing wasn't successful. Closes #1628
**Checklist**

Fix rules not able to target full targets (root level, no modifier)

---

packages/app/src/renderer/app/components/environment-settings/environment-settings.component.ts
packages/app/src/renderer/app/components/header/header.component.html
packages/app/src/renderer/app/components/menus/environments-menu/environments-menu.component.html
packages/app/src/renderer/app/components/menus/environments-menu/environments-menu.component.ts
packages/app/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.ts
packages/app/src/renderer/app/libs/utils.lib.ts
packages/app/src/renderer/app/services/deploy.service.ts
packages/app/src/renderer/app/stores/reducer.ts
packages/app/src/renderer/styles/boostrap-overrides.scss
packages/app/test/libs/environments.ts

- Do not use the environment status to display a cloud instance status (but only for the desktop version).
- Update the header's play button behavior on desktop to only react to the local server status and correctly stop the local server instead of the cloud one.
- Display both local and cloud URLs when deployed in the main environment menu with status indicators.
- For better consistency, remove the right inner shadow green indicator (environment menu item) and replace by icons indicators for both local and remote (see above). Closes #1738
**Checklist**

Improve desktop local and cloud instances running state

---

packages/app/test/specs/schema-validation.spec.ts
packages/cli/README.md
packages/cli/src/commands/dockerize.ts
packages/cli/src/commands/start.ts
packages/cli/src/commands/validate.ts
packages/cli/src/constants/command.constants.ts
packages/cli/src/libs/data.ts
packages/cli/src/libs/utils.ts
packages/cli/test/specs/validate-command.test.ts
packages/commons/src/constants/environment-schema.constants.ts

Validates Mockoon environment's data files.
Creates a new way to build the environment schema: auto repairing with defaults and failovers, and non-repairing to allow validation. Closes #1754
**Checklist**

Add a validate command for the CLI

---

packages/app/build-configs/electron-builder.linux.js
packages/app/build-configs/test/electron-builder.linux.js

Something recently changed in electron-builder that changed the executable name and used "Mockoon" with a capital M (it reverted to use the productName).
Closes #1796
**Checklist**

Fix launch error on Ubuntu
