src/app/components/environment-logs.component.html
"Caught" is the past tense of "catch". Please ignore if this is intentional
=> "Catched" -> "caught"

src/app/libs/dummy-helpers.lib.ts
Parse body for all content types otherwise it return the defaultValue
=> Try to parse body for all content types

README.md
Just passing along and saw some typos in the README; nothing too serious!
=> Fixed some typos, grammar and punctuation in README

src/electron-files/electron-main.js
- Added "Hide" button
- Added "Hide Others" button
- Added keyboard shortcut for "Settings"
=> Improved menu

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, package-lock.json, package.json, src/app/config.ts, src/electron-files/electron-main.js, src/electron-files/package.json
=> Update repository URL to use new organization

src/app/components/headers-list.component.html, src/styles.scss
Added the pointer cursor to a few things, and updated tooltips
=> Improved user interaction

package-lock.json, package.json, src/app/libs/dummy-helpers.lib.ts
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*
Add `now` helper displaying current time, with format option
#96
=> Add new `now` helper to display current date in templating

src/app/services/data.service.ts
Formatted the JSON output of Mockoon to make it more human readable and source control friendly
=> Updated JSON output

src/app/app.component.html
=> Update UI to reflect server binding on multiple network interfaces

README.md
Sorry for disregarding your PR template, hope a quick little README change doesn't require a new issue to be created 😅
=> Update README screenshot to the new URL

src/app/app.component.html, src/app/app.component.ts
Update component form value instead of store. Store will be updated through valueChanges subscription anyway.
Closes #147
=> Immediately show body formatting changes

src/electron-files/electron-main.js
=> Replace App menu "help" link with Spectrum community

src/app/app.component.html, src/app/services/toasts.service.ts
=> Use ng-bootstrap new toasts

electron-builder.json, package-lock.json, package.json
- move electron builder config in a separated file
- add deb, rpm and snap Linux binaries formats
closes #163 #162
=> Add more Linux binaries formats

src/app/libs/migrations.lib.ts, src/app/services/environments.service.ts
=> Ensure that route responses UUID are renewed after a duplicate

.github/workflows/ci.yml, package-lock.json, package.json, src/app/services/environments.service.ts, test/lib/tests.ts
- update electron to v6.0.10
- update Spectron
- add Spectron config (remote debugging port)
- change electron dialog methods calls to use promises
Closes #161
=> Update Electron to v6

src/app/stores/reducer.ts, test/lib/helpers.ts, test/proxy.spec.ts, test/routes-add-remove-triggers-restart.spec.ts
=> Display restart needed indicator when deleting and adding a route

src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/libs/migrations.lib.ts, src/app/pipes/truncate.pipe.ts, src/app/services/environments.service.ts, src/app/types/route.type.ts, src/styles.scss, test/data/basic-data/environments.json, test/data/basic-data/settings.json, test/data/dev/environments.json, test/data/dev/settings.json, test/data/first-load/settings.json, test/data/proxy/environments.json, test/data/proxy/settings.json, test/data/responses-rules/environments.json, test/data/responses-rules/settings.json
- Add label field
- Update test data
- Add truncate pipe
- Display label in route responses dropdown
- Remove status code label
Closes #170
=> Add route response label field

src/app/app.component.html, src/app/components/headers-list.component.ts, src/app/libs/migrations.lib.ts, src/app/services/schemas-builder.service.ts, src/app/services/server.service.ts, src/app/stores/reducer.ts, src/app/types/environment.type.ts, src/styles.scss, test/data/basic-data/environments.json, test/data/dev/environments.json, test/data/migrations/10/environments.json, test/data/proxy/environments.json, test/data/responses-rules/environments.json, test/lib/helpers.ts, test/migrations.spec.ts, test/proxy.spec.ts
Support adding custom request and response headers for proxy mode
Test for headers properties presence
=> Custom proxy request/response headers

src/app/app.component.html, src/app/app.component.ts, src/app/components/settings-modal.component.html, src/app/services/settings.service.ts
Provide a setting to determine whether or not the route name should be truncated in the route list
None
When you have many routes that start with the same text, it's hard to know which route is the one you're looking for
Locally
#227
=> feat(226): Add setting Truncate route name in list

src/app/libs/template-parser.lib.ts
** Summary **
Adds a base64 handlebars helper function to convert the input to a base64 string
Also adds a newline handlebars helper due to the difficulty of doing complex handlebars strings with newlines inside.
**Usage sample**
{
"file": "{{#base64}} FirstName,LastName,CountryCode {{newLine}} {{# repeat  10 comma=false}}{{ faker 'name.firstName' }},{{ faker 'name.lastName' }},{{ faker 'address.countryCode' }} {{newLine}} {{/ repeat}}{{/base64}}"
}
Issue: https://github.com/mockoon/mockoon/issues/331
We wanted to be able to return a dynamically generated base64 encoded CSV file
Tested using the sample input above.
Closes #331
=> Add handlebars helper to convert to base64

README.md
Closes #424 
Fix README to avoid error when running brew commands in macOS.
**Checklist**
Not relevant since this PR is simply a document fix.
=> docs: Fix brew commands in README.md

src/renderer/app/components/routes-menu/routes-menu.component.html, src/renderer/app/components/routes-menu/routes-menu.component.ts, src/renderer/app/services/environments.service.ts, src/renderer/app/stores/actions.ts, src/renderer/app/stores/reducer.ts, src/renderer/app/stores/store.ts, test/suites/routes-filter.spec.ts
Closes #257
Added new feature to filter routes
- Adding a new input to filter
- Adding a button to reset the filter
- Reset routes filter when adding a new route
- Reset routes filter when switching env
- Reset routes filter when duplicating route to selected environment
**Checklist**
=> Add routes-filter

src/renderer/app/components/environment-logs.component.html, src/renderer/app/components/environment-logs.component.ts, src/renderer/app/models/environment-logs.model.ts, src/renderer/app/services/environments.service.ts
createRouteFromLog: update encoding headers
Indicate response content encoding in ui
Closes #479
**Checklist**
=> Closes #479

.github/workflows/binaries-build.yml, electron-builder.json, src/main/app.ts, src/main/libs/update.ts
Add portable build version for Windows
Closes #430 
**Checklist**
=> Add portable build version

packages/commons-server/src/libs/templating-helpers/helpers.ts, packages/commons-server/test/suites/templating-helpers/helpers.spec.ts
Closes #655
**Parent issue**
Closes #insert_issue_number_here
**Checklist**
=> Add lowercase and uppercase helpers

packages/commons-server/src/libs/templating-helpers/helpers.ts, packages/commons-server/src/libs/utils.ts, packages/commons-server/test/suites/templating-helpers/helpers.spec.ts
=> Add base64Decode helper

.github/workflows/ci.yml, packages/cli/README.md, packages/cli/package.json, packages/commons-server/package.json
=> Remove Node.js 12 support for the CLI

packages/commons-server/src/libs/server/server.ts, packages/desktop/test/libs/environments-proxy.ts, packages/desktop/test/specs/proxy.spec.ts
=> Fix prefix not being removed when proxying to a prefixed endpoint

packages/desktop/src/renderer/app/app.component.ts, packages/desktop/src/renderer/app/components/context-menu/context-menus.ts, packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.ts, packages/desktop/src/renderer/app/libs/utils.lib.ts, packages/desktop/src/renderer/app/models/context-menu.model.ts, packages/desktop/test/libs/routes.ts, packages/desktop/test/specs/clipboard-copy.spec.ts, packages/desktop/test/specs/environment-restart-triggers.spec.ts, packages/desktop/test/specs/routes-create-delete.spec.ts
=> Add route context menu entry to copy the full endpoint path

packages/commons-server/src/libs/utils.ts
Closes https://github.com/mockoon/mockoon/issues/689
Technical implementation details
Checklist
=> Fix decodeURI process crash

packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.html, packages/desktop/src/renderer/styles/styles.scss
=> Make route responses dropdown menu width equal to its parent

packages/commons-server/src/constants/common.constants.ts, packages/commons-server/src/libs/response-rules-interpreter.ts, packages/commons-server/src/libs/server/server.ts, packages/commons-server/src/libs/utils.ts, packages/desktop/src/renderer/app/constants/routes.constants.ts, packages/desktop/test/specs/responses-rules.spec.ts
=> Add support for parsing application/soap+xml Content-Type

packages/commons-server/src/libs/response-rules-interpreter.ts, packages/commons-server/src/libs/templating-helpers/request-helpers.ts, packages/commons-server/src/libs/utils.ts, packages/commons-server/test/suites/response-rules/response-rules-interpreter.spec.ts, packages/commons-server/test/suites/templating-helpers/request-helpers.spec.ts, packages/desktop/test/data/mock-envs/response-rules.json, packages/desktop/test/specs/responses-rules.spec.ts
=> Add support in templating helpers and rules for properties with dots

.github/ISSUE_TEMPLATE/Release_checklist.md, CONTRIBUTING.md, packages/desktop/src/main/libs/update.ts, packages/desktop/src/renderer/app/components/modals/changelog-modal/changelog-modal.component.ts, packages/desktop/src/renderer/app/modules-config/markdown.config.ts, packages/desktop/src/shared/config.ts
- get latest release version from api.mockoon.com for auto update
- load the changelog from mockoon.com/desktop-changelogs-markdown/x.x.x.md
- Link the changelog to the public page on the website
- ensure images src and links in the changelog are all absolute
Closes #769
**Checklist**
=> New release system

packages/desktop/src/renderer/styles/styles.scss
=> Make desktop column resizers more visible

packages/commons-server/src/libs/templating-helpers/helpers.ts, packages/commons-server/test/suites/templating-helpers/helpers.spec.ts
=> Implement parseInt helper and tests

packages/commons-server/src/libs/templating-helpers/helpers.ts, packages/commons-server/test/suites/templating-helpers/helpers.spec.ts
=> Modify date helper to allow query params

packages/commons-server/src/libs/server/server.ts, packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.ts, packages/desktop/src/renderer/app/services/remote-config.service.ts, packages/desktop/src/renderer/app/stores/store.ts, packages/desktop/test/data/mock-envs/headers.json, packages/desktop/test/specs/headers.spec.ts
=> Fix file mime type not reverting to env content type

packages/desktop/src/renderer/app/stores/reducer.ts
=> Fix route duplicated to env not being save to JSON

packages/desktop/scripts/migrate-tests.js, packages/desktop/src/renderer/app/services/data.service.ts, packages/desktop/test/data/mock-envs/schema-uuid-dedup-1.json, packages/desktop/test/data/mock-envs/schema-uuid-dedup-2.json, packages/desktop/test/data/mock-envs/schema-uuid-dedup-3.json, packages/desktop/test/specs/schema-validation.spec.ts
=> Add data bucket uuid deduplication at environment load time

packages/desktop/src/renderer/app/constants/routes.constants.ts, packages/desktop/src/renderer/app/libs/utils.lib.ts
Also add text/xml to the autocomplete list
Closes #798
**Checklist**
=> Add editor syntax highlighting for text/xml

packages/commons-server/package-lock.json, packages/commons-server/package.json, packages/commons-server/src/libs/templating-helpers/helpers.ts, packages/desktop/test/data/mock-envs/templating.json, packages/desktop/test/specs/templating.spec.ts
Replaced by Fakerjs method
Closes #829
**Checklist**
=> Remove bson-objectid dependency

packages/commons-server/src/libs/server/server.ts, packages/commons-server/src/libs/templating-helpers/faker-wrapper.ts, packages/commons-server/test/suites/templating-helpers/faker-wrapper.spec.ts
- Make the faker helper works with SafeStrings
- remove stringify from faker helper to allow better compatibility with some returned values and other helpers (arrays)
- Correctly surface errors from data buckets parsing Closes #880
Closes #867
Closes #866
**Checklist**
=> Templating helpers fixes

packages/desktop/src/renderer/app/components/menus/routes-menu/routes-menu.component.html
- Make full folder clickable to collapse
- Change folder color to white
**Checklist**
=> Folders improvements

packages/desktop/src/renderer/app/components/modals/settings-modal/settings-modal.component.html, packages/desktop/src/renderer/app/components/modals/settings-modal/settings-modal.component.ts, packages/desktop/src/renderer/app/constants/settings-schema.constants.ts, packages/desktop/src/renderer/app/services/environments.service.ts, packages/desktop/src/shared/models/settings.model.ts, packages/desktop/test/data/mock-settings/settings.json, packages/desktop/test/libs/settings.ts, packages/desktop/test/specs/settings.spec.ts
=> Auto start environments on application load

CONTRIBUTING.md, packages/commons/src/constants/environment-schema.constants.ts, packages/commons/src/models/route.model.ts, packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.ts, packages/desktop/src/renderer/styles/styles.scss, packages/desktop/test/specs/ui-interactions.spec.ts
Added the following methods:
* PROPFIND
* PROPPATCH
* MKCOL
* COPY
* MOVE
* LOCK
* UNLOCK
Closes #937
**Checklist**
=> Add support of WebDAV's HTTP Methods for Distributed Authoring

packages/cli/docker/Dockerfile
=> Expose port 3000 by default in dockerfile

packages/commons-server/src/libs/response-rules-interpreter.ts, packages/commons-server/src/libs/server/server.ts, packages/commons-server/test/suites/response-rules/response-rules-interpreter.spec.ts, packages/commons/src/constants/environment-schema.constants.ts, packages/commons/src/models/route.model.ts, packages/desktop/src/renderer/app/components/custom-select/custom-select.component.html, packages/desktop/src/renderer/app/components/route-response-rules/route-response-rules.component.ts
- Remove input-group causing overflow on app-custom-select
- Fix uncaught errors message not being set as body in errorHandler Closes #586
**Checklist**
=> Add new regex insensitive response rules

package-lock.json, packages/desktop/src/renderer/app/app.component.html, packages/desktop/src/renderer/app/components/environment-logs/environment-logs.component.html, packages/desktop/test/libs/environments-logs.ts
=> Improve placement of logs delete button

packages/cli/README.md, packages/cli/docker/Dockerfile
=> Add healthcheck support to Dockerized CLI

.github/workflows/release-libs.yml
=> Added arm64 architecture to cli docker image

.github/workflows/ci.yml, .github/workflows/release-desktop.yml, .github/workflows/release-libs.yml, packages/cli/docker/Dockerfile, packages/cli/package-lock.json, packages/cli/package.json, packages/commons-server/package-lock.json, packages/commons-server/package.json, packages/serverless/package-lock.json, packages/serverless/package.json
Updates node version.
Closes #959
=> updates node version

packages/cli/package-lock.json, packages/commons-server/package-lock.json, packages/commons-server/package.json, packages/commons-server/src/libs/server/crud.ts, packages/commons/package-lock.json, packages/commons/package.json, packages/commons/src/constants/environment-schema.constants.ts, packages/commons/src/libs/migrations.ts, packages/commons/src/libs/schema-builder.ts, packages/commons/src/libs/utils.ts, packages/desktop/package-lock.json, packages/desktop/package.json, packages/desktop/src/renderer/app/services/data.service.ts, packages/desktop/src/renderer/app/services/environments.service.ts, packages/desktop/src/renderer/app/services/telemetry.service.ts, packages/desktop/src/renderer/app/services/toasts.service.ts, packages/desktop/test/specs/export-openapi.spec.ts, packages/desktop/test/specs/external-changes-watcher.spec.ts, packages/desktop/test/specs/schema-validation.spec.ts, packages/serverless/package-lock.json
=> Remove uuid package and use crypto.randomUUID()

packages/desktop/src/renderer/app/app.component.ts, packages/desktop/src/renderer/app/components/environment-logs/environment-logs.component.html, packages/desktop/src/renderer/app/components/environment-logs/environment-logs.component.ts, packages/desktop/src/renderer/app/components/header/header.component.html, packages/desktop/src/renderer/app/components/header/header.component.ts, packages/desktop/src/renderer/app/components/menus/environments-menu/environments-menu.component.html, packages/desktop/src/renderer/app/components/menus/environments-menu/environments-menu.component.ts, packages/desktop/src/renderer/app/components/svg/svg.component.html, packages/desktop/src/renderer/app/components/svg/svg.component.ts, packages/desktop/src/renderer/app/libs/utils.lib.ts, packages/desktop/src/renderer/app/services/environments.service.ts, packages/desktop/src/renderer/app/services/events.service.ts, packages/desktop/src/renderer/app/services/server.service.ts, packages/desktop/src/renderer/app/stores/actions.ts, packages/desktop/src/renderer/app/stores/reducer-utils.ts, packages/desktop/src/renderer/app/stores/reducer.ts, packages/desktop/test/data/mock-envs/empty2.json, packages/desktop/test/libs/environments-logs.ts, packages/desktop/test/libs/environments.ts, packages/desktop/test/libs/navigation.ts, packages/desktop/test/specs/environment-logs-recording.spec.ts, packages/desktop/test/tools/documentation.spec.ts
=> Add recording option

packages/desktop/src/main/app.ts
=> For Snap packages, set data folder to SNAP_USER_COMMON

packages/serverless/README.md
Updating the serveless package's instructions with details on how to deploy your mock API to Netlify's serverless
**Checklist**
=> Add Netlify instructions to the serverless package readme

packages/commons-server/src/libs/templating-helpers/data-helpers.ts, packages/commons-server/test/suites/templating-helpers/data-helpers.spec.ts
=> Make `data` helpers compatible with safestring

packages/commons-server/src/libs/response-rules-interpreter.ts, packages/commons-server/src/libs/server/server.ts, packages/commons-server/test/suites/response-rules/response-rules-interpreter.spec.ts
**Issue**
https://github.com/mockoon/mockoon/issues/988
**Checklist**
=> Allow helpers in response rule value

packages/commons-server/src/libs/templating-helpers/helpers.ts, packages/commons-server/test/suites/templating-helpers/helpers.spec.ts
=> [Feature Request] - Issue 1103 Add helper object Add helper filter

packages/commons-server/src/libs/templating-helpers/helpers/eq.ts, packages/commons-server/test/suites/templating-helpers/helpers.spec.ts
Update `eq` helper.
Make it works with any values.
Closes #1114 
**Checklist**
=> 1114 - [Feature] Make eq helper works with strings

.gitignore, packages/cli/src/libs/data.ts, packages/cli/test/specs/data-loading.spec.ts
=> Better report errors when loading data files and avoid parsing yml files

packages/desktop/src/renderer/app/constants/settings-schema.constants.ts, packages/desktop/src/renderer/app/models/callback.model.ts, packages/desktop/src/renderer/app/models/databucket.model.ts, packages/desktop/src/renderer/app/models/main-api.model.ts, packages/desktop/src/renderer/app/models/settings.model.ts, packages/desktop/src/renderer/app/models/store.model.ts, packages/desktop/src/renderer/app/services/environments.service.ts, packages/desktop/src/renderer/app/services/migration.service.ts, packages/desktop/src/renderer/app/services/settings.service.ts, packages/desktop/src/renderer/app/services/storage.service.ts, packages/desktop/src/renderer/app/services/ui.service.ts, packages/desktop/src/renderer/app/stores/actions.ts
=> Remove old migrations system (pre 1.7.0)

packages/cli/src/commands/export.ts, packages/cli/src/commands/import.ts, packages/cli/src/commands/start.ts, packages/cli/src/constants/cli-messages.constants.ts, packages/cli/src/libs/data.ts, packages/cli/test/data/openapi/petstore-broken.json, packages/cli/test/data/openapi/petstore-broken.yaml, packages/cli/test/specs/data-validation.spec.ts, packages/commons-server/src/libs/openapi-converter.ts, packages/commons-server/test/data/openapi/openapi-v3.yaml, packages/commons-server/test/suites/openapi-converter/openapi-converter.spec.ts
Also remove too many envs error in import/export commands as i/o flags are not multiple anyway. Closes #1229
**Checklist**
=> Fix CLI OpenAPI errors not being reported for JSON

packages/commons-server/src/libs/templating-helpers/global-helpers.ts, packages/commons-server/test/suites/templating-helpers/global-helpers.spec.ts
=> Add default value to getGlobalVar helper

packages/desktop/src/main/libs/menu.ts, packages/desktop/src/renderer/app/app.component.html, packages/desktop/src/renderer/app/app.component.ts, packages/desktop/src/renderer/app/app.module.ts, packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.html, packages/desktop/src/renderer/app/components/header/header.component.html, packages/desktop/src/renderer/app/components/header/header.component.ts, packages/desktop/src/renderer/app/components/menus/environments-menu/environments-menu.component.html, packages/desktop/src/renderer/app/components/menus/routes-menu/routes-menu.component.html, packages/desktop/src/renderer/app/components/modals/welcome-modal/welcome-modal.component.html, packages/desktop/src/renderer/app/components/modals/welcome-modal/welcome-modal.component.ts, packages/desktop/src/renderer/app/components/svg/svg.component.html, packages/desktop/src/renderer/app/components/svg/svg.component.ts, packages/desktop/src/renderer/app/components/tour/tour.component.html, packages/desktop/src/renderer/app/components/tour/tour.component.ts, packages/desktop/src/renderer/app/directives/tour-step.directive.ts, packages/desktop/src/renderer/app/models/tour.model.ts, packages/desktop/src/renderer/app/services/api.service.ts, packages/desktop/src/renderer/app/services/tour.service.ts, packages/desktop/src/renderer/styles/bootstrap-variables.scss, packages/desktop/src/renderer/styles/styles.scss, packages/desktop/test/specs/changelog-modal.spec.ts, packages/desktop/test/specs/first-load.spec.ts, tsconfig.json
=> Update welcome screen and add tour

packages/commons-server/src/libs/server/server.ts, packages/desktop/test/data/mock-envs/callbacks.json, packages/desktop/test/specs/callbacks.spec.ts
=> Fix callbacks not called when body type is FILE

packages/desktop/src/renderer/app/app.component.ts, packages/desktop/src/renderer/app/app.module.ts, packages/desktop/src/renderer/app/components/banner/banner.component.ts, packages/desktop/src/renderer/app/models/remote-config.model.ts, packages/desktop/src/renderer/app/services/remote-config.service.ts, packages/desktop/src/renderer/app/services/user.service.ts
Remote config was fetched from Firebase. We migrate to allow for more flexibility (custom config depending on the app version, user logged in or not, etc.)
**Checklist**
=> Migrate from firebase remote config to custom API endpoint

packages/commons-server/src/libs/response-rules-interpreter.ts, packages/commons-server/test/suites/response-rules/response-rules-interpreter.spec.ts, packages/commons/src/constants/environment-schema.constants.ts, packages/commons/src/models/route.model.ts, packages/desktop/src/renderer/app/components/route-response-rules/route-response-rules.component.ts
=> Add global variables support in rules

packages/commons-server/src/libs/templating-helpers/helpers/index.ts, packages/commons-server/src/libs/templating-helpers/helpers/json-parse.ts, packages/commons-server/test/suites/templating-helpers/helpers.spec.ts, packages/desktop/src/renderer/app/constants/autocomplete.constant.ts
=> Add jsonParse templating helper

packages/serverless/README.md
Fixed inaccuracy in the documentation about implementing _serverless_ with Firebase/GCP Functions.
**Checklist**
=> 📝 fix documentation with serverless examples

packages/commons-server/src/libs/server/server.ts
This PR fixes the issue of not parsing databucket templates in callbacks. Root cause was, the databucket ids which specified in any of the callback has not been pre-processed when the route is initializing. It only considered the databuckets in response body.
As the fix, now all relevant callbacks will also be scanned for databuckets and be pre-processed.
**Checklist**
Closes #1302
=> Fix for databuckets templates not processing in callback invocations

packages/cli/src/libs/data.ts
=> Fix CLI port and hostname flags not used when running an OpenAPI file

packages/commons-server/src/libs/server/server.ts, packages/desktop/test/data/mock-envs/databuckets.json, packages/desktop/test/specs/databuckets.spec.ts
=> parse nested buckets when they are not referenced elsewhere

packages/desktop/src/renderer/app/app.component.ts, packages/desktop/src/renderer/app/components/context-menu/context-menus.ts, packages/desktop/src/renderer/app/services/environments.service.ts, packages/desktop/test/data/mock-envs/basic-folder-2-routes.json, packages/desktop/test/libs/context-menu.ts, packages/desktop/test/specs/folders.spec.ts
Create a new item on the folder menu for the toggle of the complete folder. 
**Checklist**
Closes #1188
=> Toggle folders #1188

packages/commons-server/src/libs/server/server.ts
Firebase functions already parse the body, and we need to check this before listening to the 'data' event as it may never be emitted.
Closes #1385
**Checklist**
Closes #1385
=> Check if body was already parsed in the body parser

packages/desktop/src/renderer/app/directives/resize-column.directive.ts, packages/desktop/src/renderer/styles/styles.scss
=> Force drag handler to stay styled when dragging, reduce animation time

packages/cli/package-lock.json, packages/cli/package.json
Updating oclif dependencies to remove the sub `lodash.template`, which has an unpatched vulnerability (https://github.com/advisories/GHSA-35jh-r3h4-6jhm).
- Updates `@oclif/core` from 3.26.4 to 3.27.0 (The version 4.x.x is available, but I'm avoiding breaking changes)
- Updates `@oclif/plugin-help` from 6.0.21 to 6.2.7
- Updates `@oclif/test` from 3.2.11 to 3.2.15 (The version 4.x.x is available, but I'm avoiding breaking changes)
- Updates `oclif` from 4.9.0 to 4.14.12
**Checklist**
Closes #1469
=> Bump @oclif/core, @oclif/plugin-help, @oclif/test and oclif in /packages/cli

packages/commons-server/src/libs/response-rules-interpreter.ts, packages/commons-server/test/suites/response-rules/response-rules-interpreter.spec.ts
=> Add support for templating in rules modifier

packages/desktop/src/renderer/app/stores/reducer.ts
=> Fix last opened environment not saved if not explicitely selected

packages/commons-server/src/libs/server/crud.ts, packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.html, packages/desktop/test/data/mock-envs/crud.json, packages/desktop/test/libs/routes.ts, packages/desktop/test/specs/crud.spec.ts
=> Add support for dot notation for CRUD crudKey

packages/commons-server/src/libs/templating-helpers/helpers/index.ts, packages/commons-server/src/libs/templating-helpers/helpers/jwt.ts, packages/commons-server/test/suites/templating-helpers/helpers.spec.ts
=> Add jwtPayload and jwtHeader helpers

packages/desktop/src/renderer/app/components/environment-logs/environment-logs.component.html, packages/desktop/src/renderer/app/components/environment-logs/environment-logs.component.ts, packages/desktop/src/renderer/app/stores/store.ts
Use date-fns formatDistanceFromNow
Closes #1430
**Checklist**
=> Display time in a human readable format in the logs

packages/commons-server/src/libs/templating-helpers/helpers/stringify.ts, packages/commons-server/test/suites/templating-helpers/helpers.spec.ts
=> Update stringify helper to be compatible with SafeString

packages/cloud/src/models/sync.model.ts, packages/desktop/src/renderer/app/app.module.ts, packages/desktop/src/renderer/app/components/environment-logs/environment-logs.component.html, packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.html, packages/desktop/src/renderer/app/components/header/header.component.html, packages/desktop/src/renderer/app/components/menus/callbacks-menu/callbacks-menu.component.html, packages/desktop/src/renderer/app/components/menus/databuckets-menu/databuckets-menu.component.html, packages/desktop/src/renderer/app/components/menus/environments-menu/environments-menu.component.html, packages/desktop/src/renderer/app/components/menus/routes-menu/routes-menu.component.html, packages/desktop/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.html, packages/desktop/src/renderer/app/components/modals/manage-instances-modal/manage-instances-modal.component.html, packages/desktop/src/renderer/app/components/svg/svg.component.scss, packages/desktop/src/renderer/app/components/svg/svg.component.ts, packages/desktop/src/renderer/app/components/team-presence/team-presence.component.html, packages/desktop/src/renderer/app/components/team-presence/team-presence.component.scss, packages/desktop/src/renderer/app/components/team-presence/team-presence.component.ts, packages/desktop/src/renderer/app/services/sync.service.ts, packages/desktop/src/renderer/styles/styles.scss
- create new presence component
- display avatars list in the header and in the environment list  Closes #1512
**Checklist**
=> Improve Cloud team presence indicators

packages/commons-server/src/libs/templating-helpers/helpers/index.ts, packages/commons-server/src/libs/templating-helpers/helpers/isValidDate.ts, packages/commons-server/test/suites/templating-helpers/helpers.spec.ts, packages/desktop/src/renderer/app/constants/autocomplete.constant.ts
- add missing helper to autocomplete Closes #1510
**Checklist**
=> Add new isValidDate templating helper

packages/commons-server/src/libs/templating-helpers/helpers/eq.ts, packages/commons-server/src/libs/templating-helpers/helpers/filter.ts
=> Make filter and eq helpers compatible with SafeString

packages/commons-server/src/libs/templating-helpers/helpers/index.ts, packages/commons-server/src/libs/templating-helpers/helpers/uuid.ts
=> Add uuid templating helper

packages/commons-server/src/libs/server/server.ts, packages/commons/src/models/server.model.ts, packages/desktop/package-lock.json, packages/desktop/test/data/mock-envs/templating.json, packages/desktop/test/specs/templating.spec.ts
Files are *not* saved anywhere, only their metadata are added to the body (filename, type, size and form field) Closes #1445
**Checklist**
=> Add support for storing multipart files metadata

packages/commons-server/src/libs/templating-helpers/data-helpers.ts, packages/commons-server/test/suites/templating-helpers/data-helpers.spec.ts, packages/desktop/src/renderer/app/constants/autocomplete.constant.ts
=> Add setData helper

packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.html, packages/desktop/src/renderer/styles/boostrap-overrides.scss, packages/desktop/test/libs/routes.ts, packages/desktop/test/libs/utils.ts
=> Add a responses counter

packages/commons-server/src/libs/server/crud.ts, packages/desktop/test/data/mock-envs/crud.json, packages/desktop/test/specs/crud.spec.ts
=> Add support for auto increment of numeric ids in CRUD routes

packages/commons-server/src/libs/response-rules-interpreter.ts, packages/commons-server/test/suites/response-rules/response-rules-interpreter.spec.ts, packages/commons/src/constants/environment-schema.constants.ts, packages/commons/src/models/route.model.ts, packages/desktop/src/renderer/app/components/route-response-rules/route-response-rules.component.ts
=> Add custom templating rule

packages/commons-server/src/libs/server/admin-api.ts, packages/commons-server/src/libs/server/server.ts, packages/commons-server/test/data/environments/test-env.json, packages/commons-server/test/suites/server/admin-api/data-buckets.spec.ts, packages/commons-server/test/suites/server/admin-api/env-vars.spec.ts, packages/commons-server/test/suites/server/admin-api/global-vars.spec.ts
=> Add GET routes to the admin API

packages/desktop/src/renderer/app/libs/utils.lib.ts
=> Add correct protocol when copying route path

packages/commons-server/src/libs/utils.ts, packages/commons-server/test/specs/templating-helpers/request-helpers.test.ts, packages/commons-server/test/specs/utils.test.ts
=> Add support for groups in parentheses in JSONPath validation

packages/commons-server/src/libs/server/server.ts, packages/commons/src/models/environment.model.ts, packages/commons/src/models/events.model.ts, packages/commons/src/models/server.model.ts, packages/desktop/src/main/libs/server-management.ts, packages/desktop/src/renderer/app/components/environment-databuckets/environment-databuckets.component.html, packages/desktop/src/renderer/app/components/environment-databuckets/environment-databuckets.component.ts, packages/desktop/src/renderer/app/components/menus/databuckets-menu/databuckets-menu.component.html, packages/desktop/src/renderer/app/components/menus/databuckets-menu/databuckets-menu.component.ts, packages/desktop/src/renderer/app/models/main-api.model.ts, packages/desktop/src/renderer/app/models/store.model.ts, packages/desktop/src/renderer/app/services/server.service.ts, packages/desktop/src/renderer/app/stores/actions.ts, packages/desktop/src/renderer/app/stores/reducer.ts, packages/desktop/src/renderer/app/stores/store.ts
- Add indicator showing if data bucket is correctly parsed
- emit event from server when parsed
- also fix admin API case sensitive data bucket lookup Closes #1581
**Checklist**
=> Add feedback for data buckets

packages/commons-server/package-lock.json, packages/commons-server/package.json, packages/commons-server/src/libs/response-rules-interpreter.ts, packages/commons-server/test/specs/response-rules/response-rules-interpreter.test.ts
=> Add support for JSON schema formats

packages/desktop/test/wdio-linux.conf.ts
=> Fix linux tests

packages/commons-server/src/libs/utils.ts, packages/commons-server/test/specs/utils.test.ts
=> Add support for jsonpath filters child properties

packages/desktop/src/renderer/app/components/dropdown-menu/dropdown-menu.component.html, packages/desktop/src/renderer/app/components/dropdown-menu/dropdown-menu.component.ts, packages/desktop/src/renderer/app/components/environment-callbacks/environment-callbacks.component.ts, packages/desktop/src/renderer/app/components/environment-logs/environment-logs.component.ts, packages/desktop/src/renderer/app/components/environment-routes/environment-routes.component.ts, packages/desktop/src/renderer/app/components/menus/callbacks-menu/callbacks-menu.component.ts, packages/desktop/src/renderer/app/components/menus/databuckets-menu/databuckets-menu.component.ts, packages/desktop/src/renderer/app/components/menus/environments-menu/environments-menu.component.html, packages/desktop/src/renderer/app/components/menus/environments-menu/environments-menu.component.ts, packages/desktop/src/renderer/app/components/menus/routes-menu/routes-menu.component.ts, packages/desktop/src/renderer/app/components/modals/manage-instances-modal/manage-instances-modal.component.ts, packages/desktop/src/renderer/app/constants/settings-schema.constants.ts, packages/desktop/src/renderer/app/services/environments.service.ts, packages/desktop/src/renderer/app/stores/reducer.ts, packages/desktop/src/renderer/styles/styles.scss, packages/desktop/src/shared/models/settings.model.ts, packages/desktop/test/libs/environments.ts
Also refactor env menu and dropdown component to use new input signals and control flow Closes #1398
**Checklist**
Closes #1398
=> Save recently opened local envs in a list

packages/cli/test/data/envs/petstore-imported.json, packages/commons-server/src/libs/openapi-converter.ts, packages/commons/src/libs/schema-builder.ts, packages/desktop/src/renderer/app/services/environments.service.ts, packages/desktop/test/data/res/import-openapi/references/aws-cloudfront-v3.json, packages/desktop/test/data/res/import-openapi/references/aws-server-v3.json, packages/desktop/test/data/res/import-openapi/references/custom-schema-no-prefix-v2.json, packages/desktop/test/data/res/import-openapi/references/custom-schema-no-prefix-v3.json, packages/desktop/test/data/res/import-openapi/references/custom-schema-v2.json, packages/desktop/test/data/res/import-openapi/references/custom-schema-v3.json, packages/desktop/test/data/res/import-openapi/references/datagov-v2.json, packages/desktop/test/data/res/import-openapi/references/giphy-v2.json, packages/desktop/test/data/res/import-openapi/references/github-v2.json, packages/desktop/test/data/res/import-openapi/references/petstore-v2.json, packages/desktop/test/data/res/import-openapi/references/petstore-v3.json, packages/desktop/test/data/res/import-openapi/references/shutterstock-v3.json, packages/desktop/test/data/res/import-openapi/references/slack-v2.json, packages/desktop/test/data/res/import-openapi/references/youtube-v3.json
This is a follow up from #1392
Closes #1593
**Checklist**
=> Add cors headers by default during OpenAPI import

packages/commons-server/src/libs/templating-helpers/helpers/find.ts, packages/commons-server/src/libs/templating-helpers/helpers/index.ts, packages/commons-server/test/specs/templating-helpers/helpers.test.ts, packages/desktop/src/renderer/app/constants/autocomplete.constant.ts
=> Add find helper

packages/commons-server/src/libs/response-rules-interpreter.ts, packages/commons-server/test/specs/response-rules/response-rules-interpreter.test.ts
=> Fix request body JSON string matching in rules

packages/cli/docker/Dockerfile
=> Update CLI Dockerfile image version to fix vulnerabilities

packages/commons-server/src/libs/server/admin-api.ts, packages/commons-server/src/libs/server/server.ts, packages/commons-server/test/specs/server/admin-api/data-buckets.test.ts
=> Add data buckets statuses to the admin API

packages/commons-server/src/libs/server/admin-api.ts, packages/commons-server/src/libs/server/server.ts, packages/commons-server/src/libs/server/sse.ts
=> Add SSE events endpoint to the admin API and stream the request logs

packages/commons-server/src/libs/server/admin-api.ts
=> Add CORS headers to admin API

packages/desktop/src/renderer/app/components/modals/command-palette-modal/command-palette-modal.component.html, packages/desktop/src/renderer/app/components/modals/command-palette-modal/command-palette-modal.component.ts, packages/desktop/src/renderer/app/services/command-palette.service.ts
Also fix method/route type display
Closes #1186
**Checklist**
=> Update command palette to search for all routes

packages/cloud/src/models/deploy-instance.model.ts, packages/desktop/src/renderer/app/components/menus/routes-menu/routes-menu.component.ts, packages/desktop/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.html, packages/desktop/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.ts, packages/desktop/src/renderer/app/components/modals/manage-instances-modal/manage-instances-modal.component.html, packages/desktop/src/renderer/app/components/svg/svg.component.html, packages/desktop/src/renderer/app/components/svg/svg.component.ts, packages/desktop/src/renderer/app/services/deploy.service.ts
=> Always enable the admin API for cloud instances

packages/desktop/build-configs/electron-builder.linux.js
=> Use core22 for Linux snap

packages/commons-server/src/libs/server/server.ts, packages/commons-server/test/data/environments/test-env.json, packages/commons-server/test/specs/server/range-header.test.ts, packages/commons/src/models/server.model.ts, packages/desktop/test/specs/file.spec.ts, packages/serverless/src/libs/serverless.ts
=> Fix path traversal vulnerability in file paths

packages/commons-server/src/libs/server/admin-api.ts, packages/commons-server/src/libs/server/server.ts, packages/commons-server/src/libs/server/sse.ts
=> Add buckets generation event to the admin API

packages/app/src/renderer/app/models/telemetry.model.ts, packages/app/src/renderer/app/services/telemetry.service.ts
Use sendBeacon instead of fetch for telemetry and add two new fields
**Checklist**
=> Add new fields and use sendBeacon

packages/commons-server/src/libs/utils.ts, packages/commons-server/test/specs/utils.test.ts
=> Add support for simple equalities in JSONPath expressions

packages/commons-server/src/libs/server/server.ts
=> Ignore upgrade headers when no ws route is present

packages/app/src/renderer/app/components/menus/environments-menu/environments-menu.component.html
=> Fix env menu items all showing the same API prefix

packages/app/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.html, packages/app/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.ts
=> Prevent deployments during subdomain check after an instance is stopped

packages/app/src/renderer/app/components/header/header.component.html
=> Play button shouldn't be interactable on web when logged out

packages/app/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.html, packages/app/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.ts
=> Improve application deployment dialog wording

packages/app/src/renderer/app/components/footer/footer.component.html, packages/app/src/renderer/app/components/footer/footer.component.ts, packages/app/src/renderer/app/components/modals/feedback-modal/feedback-modal.component.html, packages/app/src/renderer/app/components/spinner.component.ts
Polish the footer design
Closes #1767
**Checklist**
=> Display the version in the footer

packages/cli/README.md, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/export.ts, packages/cli/src/commands/import.ts, packages/cli/src/commands/start.ts, packages/cli/src/libs/data.ts, packages/cli/test/libs/helpers.ts, packages/cli/test/specs/file-watch.test.ts
=> Add new watch flag to monitor local files

packages/app/src/renderer/app/components/custom-select/custom-select.component.html, packages/app/src/renderer/app/components/custom-select/custom-select.component.ts, packages/app/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.html, packages/app/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.ts, packages/app/src/renderer/app/components/modals/manage-instances-modal/manage-instances-modal.component.html, packages/app/src/renderer/app/components/modals/manage-instances-modal/manage-instances-modal.component.ts, packages/app/src/renderer/app/constants/settings-schema.constants.ts, packages/app/src/renderer/app/stores/store.ts, packages/app/src/shared/models/settings.model.ts, packages/cloud/src/models/deploy-instance.model.ts, packages/cloud/src/models/remote-config.model.ts
- display region in deployment modal if present in the remote config.
- save last region choice in the settings
- display the region in the deployments management dialog.
- make geoip endpoint optional in remote config model. Closes #1786
**Checklist**
=> Add regions choice for cloud deployments

packages/app/src/renderer/app/components/environment-logs/environment-logs.component.html, packages/app/src/renderer/app/components/environment-logs/environment-logs.component.ts, packages/app/src/renderer/app/components/toggle/toggle.component.html, packages/app/src/renderer/app/models/common.model.ts, packages/app/src/renderer/app/models/environment-logs.model.ts, packages/app/src/renderer/app/services/data.service.ts, packages/app/src/renderer/app/services/environments.service.ts, packages/app/src/renderer/app/services/events.service.ts, packages/app/src/renderer/app/services/server.service.ts
- add switch to filter logs by origin
- fetch logs from admin API events endpoint
- update logs to store origin local or cloud
- add indicator on each log entry when not filtered Closes #1808
**Checklist**
Closes #1808
=> Display cloud logs in desktop app

packages/app/src/renderer/app/components/dropdown-menu/dropdown-menu.component.html, packages/app/src/renderer/app/components/dropdown-menu/dropdown-menu.component.ts, packages/app/src/renderer/app/components/menus/environments-menu/environments-menu.component.ts, packages/app/src/renderer/app/components/menus/routes-menu/routes-menu.component.ts, packages/app/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.html, packages/app/src/renderer/app/components/modals/deploy-instance-modal/deploy-instance-modal.component.ts, packages/app/src/renderer/app/components/modals/manage-instances-modal/manage-instances-modal.component.html, packages/app/src/renderer/app/components/modals/manage-instances-modal/manage-instances-modal.component.ts, packages/app/src/renderer/app/stores/store.ts, packages/app/test/libs/utils.ts
=> Disable ability to deploy local environments from the desktop app

packages/commons/src/libs/schema-builder.ts
=> Fix demo API embedded docs

packages/app/src/renderer/app/constants/routes.constants.ts
=> Add yaml mime types to the header autocomplete

packages/app/src/main/libs/zoom.ts
=> Add more zoom levels in the desktop application
